name: Production Test Windows

on:
  push:
    branches:
      - "master"
    paths:
      - "src/**"
      - ".github/workflows/**"
      - "package.json"
      - "package-lock.json"
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/**"
      - "package.json"
      - "package-lock.json"

jobs:
  production-test-windows:
    if: "!contains(toJSON(github.event.commits.*.message), '[SKIP TEST]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2019", "windows-2022", "windows-latest"]
        node: [12, 14, 16]
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v2

      - name: Setup the node js environment with version ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run the test-full script to update packages and run the tests.
        run: npm run test-full
